Repository Team-2m4t/Hyangyu-iOS, pull requests merged in 2022-02, with the labels that each got.

#19 [Feat] 서치 뷰 UI (#9)
  Hyangyu/Hyangyu.xcodeproj/project.pbxproj
  Hyangyu/Hyangyu/Base.lproj/Main.storyboard
  Hyangyu/Hyangyu/Resources/Constants/Const.swift
  Hyangyu/Hyangyu/Resources/Constants/URL.swift
  Hyangyu/Hyangyu/Resources/Info.plist
  Hyangyu/Hyangyu/Resources/Storyboards/Search/Search.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/Tabbar.storyboard
  Hyangyu/Hyangyu/Sources/APIModels/Auth.swift
  Hyangyu/Hyangyu/Sources/APIServices/GenericResponse.swift
  Hyangyu/Hyangyu/Sources/APIServices/LoginAPI.swift
  Hyangyu/Hyangyu/Sources/APIServices/LoginService.swift
  Hyangyu/Hyangyu/Sources/APIServices/MoyaLoggingPlugin.swift
  Hyangyu/Hyangyu/Sources/APIServices/NetworkResult.swift
  Hyangyu/Hyangyu/Sources/APIServices/PasswordAPI.swift
  Hyangyu/Hyangyu/Sources/APIServices/PasswordService.swift
  Hyangyu/Hyangyu/Sources/APIServices/SignUpAPI.swift
  Hyangyu/Hyangyu/Sources/APIServices/SignUpService.swift
  Hyangyu/Hyangyu/Sources/AppDelegate.swift
  Hyangyu/Hyangyu/Sources/AppModels/Product.swift
  Hyangyu/Hyangyu/Sources/AppModels/Search.swift
  Hyangyu/Hyangyu/Sources/AppModels/SignUpUser.swift
  Hyangyu/Hyangyu/Sources/Cells/LeftAlignedCollectionViewFlowLayout.swift
  Hyangyu/Hyangyu/Sources/Cells/MyPageCollectionViewCell.xib
  Hyangyu/Hyangyu/Sources/Cells/SearchResultCell.swift
  Hyangyu/Hyangyu/Sources/Cells/SearchResultsTableViewCell.swift
  Hyangyu/Hyangyu/Sources/Cells/SearchResultsTableViewCell.xib
  Hyangyu/Hyangyu/Sources/Cells/SearchTagCollectionViewCell.swift
  Hyangyu/Hyangyu/Sources/Extensions/UIViewController+Extensions.swift
  Hyangyu/Hyangyu/Sources/SceneDelegate.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/FindPassword/FindPasswordViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/FindPassword/FindPasswordViewController.xib
  Hyangyu/Hyangyu/Sources/ViewControllers/MyPage/ProfileEditViewController.xib
  Hyangyu/Hyangyu/Sources/ViewControllers/NewPassword/NewPasswordViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/NewPassword/NewPasswordViewController.xib
  Hyangyu/Hyangyu/Sources/ViewControllers/ResetCode/ResetCodeViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/ResetCode/ResetCodeViewController.xib
  Hyangyu/Hyangyu/Sources/ViewControllers/Search/SearchResultsViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Search/SearchViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Search/Views/SearchBarView.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Search/Views/SearchHeaderCollectionReusableView.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Search/Views/SearchResultView.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Search/Views/SearchTableViewHeaderView.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Search/Views/SearchView.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/SignIn/SignInViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/SignIn/SignInViewController.xib
  Hyangyu/Hyangyu/Sources/ViewControllers/SignUp/SignUpViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/SignUp/SignUpViewController.xib
  Hyangyu/Hyangyu/Sources/ViewControllers/ViewController.swift
  Hyangyu/Hyangyu/Sources/ViewModels/SearchResult.swift
  Hyangyu/Hyangyu/Sources/ViewModels/SearchResultsTableViewCellViewModel.swift
Labels: sorin, feat

#20 Feature/deatailpage/#17
  Hyangyu/Hyangyu.xcodeproj/project.pbxproj
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back 1.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back 1.imageset/back 1 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back 1.imageset/back 1 (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back 1.imageset/back 1.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/exhibition.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/exhibition.imageset/Group 42 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/exhibition.imageset/Group 42 (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/exhibition.imageset/exhibition.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/fair.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/fair.imageset/Group 45 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/fair.imageset/Group 45 (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/fair.imageset/fair.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/festival.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/festival.imageset/Group 44 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/festival.imageset/Group 44 (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/festival.imageset/festival.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/heart.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/heart.imageset/love 1 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/heart.imageset/love 1 (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/heart.imageset/love 1.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/poster.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/poster.imageset/Rectangle 100 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/poster.imageset/Rectangle 100.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/poster.imageset/poster.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/poster_example.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/poster_example.imageset/포스터 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/poster_example.imageset/포스터 (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/poster_example.imageset/포스터.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/report.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/report.imageset/Icon Artwork (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/report.imageset/Icon Artwork (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/report.imageset/Icon Artwork.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/share.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/share.imageset/share 1 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/share.imageset/share 1 (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/share.imageset/share 1.png
  Hyangyu/Hyangyu/Resources/Storyboards/CategoryTab.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/DetailViewPage.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/HomeTab.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/MoreReviewPage.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/MyPageTab.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/SearchTab.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/WriteReviewPage.storyboard
  Hyangyu/Hyangyu/Sources/Cells/CategoryCollectionViewCell.swift
  Hyangyu/Hyangyu/Sources/Cells/CategoryCollectionViewCell.xib
  Hyangyu/Hyangyu/Sources/SceneDelegate.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/CategoryExhibitionViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/CategoryFairViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/CategoryFestivalViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/CategoryFirstViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/CategoryViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/DetailCategoryViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/DetailPageViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/MoreReviewViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/ViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/WriteReviewViewController.swift
Labels: heesoo, feat

#22 [Feat] 탭바 UI (#21)
  Hyangyu/Hyangyu.xcodeproj/project.pbxproj
  Hyangyu/Hyangyu/Resources/Info.plist
  Hyangyu/Hyangyu/Resources/Storyboards/CategoryTab.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/Home.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/Tabbar.storyboard
  Hyangyu/Hyangyu/Sources/AppModels/ServiceDataModel.swift
  Hyangyu/Hyangyu/Sources/SceneDelegate.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/CategoryViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/TabBarViewController.swift
Labels: sorin, feat

#26 Feature/deatail page/#17
  Hyangyu/Hyangyu.xcodeproj/project.pbxproj
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back 1.imageset/back 1 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back 1.imageset/back 1 (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back 1.imageset/back 1.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back.imageset/back 1 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back.imageset/back 1 (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back.imageset/back 1.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/posterexample.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/posterexample.imageset/포스터 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/posterexample.imageset/포스터 (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/posterexample.imageset/포스터.png
  Hyangyu/Hyangyu/Resources/Info.plist
  Hyangyu/Hyangyu/Resources/Storyboards/DetailViewPage.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/MoreReviewPage.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/WriteReviewPage.storyboard
  Hyangyu/Hyangyu/Sources/Cells/ReviewCollectionViewCell.swift
  Hyangyu/Hyangyu/Sources/Cells/ReviewCollectionViewCell.xib
  Hyangyu/Hyangyu/Sources/ViewControllers/DetailPageViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/MoreReviewViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/ReviewDataModel.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/WriteReviewViewController.swift
Labels: heesoo, feat

#27 [Feat] 닉네임 변경 뷰 서버 연결 (#23)
  Hyangyu/Hyangyu.xcodeproj/project.pbxproj
  Hyangyu/Hyangyu/Resources/Constants/URL.swift
  Hyangyu/Hyangyu/Sources/APIModels/MyPage.swift
  Hyangyu/Hyangyu/Sources/APIServices/AuthAPI/LoginAPI.swift
  Hyangyu/Hyangyu/Sources/APIServices/AuthAPI/LoginService.swift
  Hyangyu/Hyangyu/Sources/APIServices/AuthAPI/PasswordAPI.swift
  Hyangyu/Hyangyu/Sources/APIServices/AuthAPI/PasswordService.swift
  Hyangyu/Hyangyu/Sources/APIServices/AuthAPI/SignUpAPI.swift
  Hyangyu/Hyangyu/Sources/APIServices/AuthAPI/SignUpService.swift
  Hyangyu/Hyangyu/Sources/APIServices/MyPageAPI/MyPageAPI.swift
  Hyangyu/Hyangyu/Sources/APIServices/MyPageAPI/MyPageService.swift
  Hyangyu/Hyangyu/Sources/AppModels/User.swift
  Hyangyu/Hyangyu/Sources/SceneDelegate.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/MyPage/ProfileEditViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Search/SearchResultsViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Search/SearchViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/SignIn/SignInViewController.swift
Labels: sorin, feat, 서버연결

#33 [feat] 카테고리탭 서버연결 완료
  Hyangyu/Hyangyu.xcodeproj/project.pbxproj
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back 1.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back 1.imageset/back 1 (1).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back 1.imageset/back 1 (2).png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/back 1.imageset/back 1.png
  Hyangyu/Hyangyu/Resources/Constants/URL.swift
  Hyangyu/Hyangyu/Resources/Info.plist
  Hyangyu/Hyangyu/Resources/Storyboards/CategoryDetailPage.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/DetailViewPage.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/Tabbar.storyboard
  Hyangyu/Hyangyu/Sources/APIModels/CagetoryDisplayResponse.swift
  Hyangyu/Hyangyu/Sources/APIServices/CategoryAPI/CategoryAPI.swift
  Hyangyu/Hyangyu/Sources/APIServices/CategoryAPI/CategoryService.swift
  Hyangyu/Hyangyu/Sources/Cells/CategoryCollectionViewCell.swift
  Hyangyu/Hyangyu/Sources/Cells/CategoryCollectionViewCell.xib
  Hyangyu/Hyangyu/Sources/Extensions/UIImageView+Extension.swift
  Hyangyu/Hyangyu/Sources/SceneDelegate.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Category/BestVC.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Category/CostVC.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Category/FreeVC.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/Category/NewVC.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/DetailCategoryViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/DetailPageViewController.swift
  Hyangyu/Hyangyu/Sources/ViewModels/ReviewDataModel.swift
Labels: heesoo, feat, 서버연결

#38 [Error] 파일명 중복으로 인한 오류 수정 (#37)
  Hyangyu/Hyangyu.xcodeproj/project.pbxproj
  Hyangyu/Hyangyu/Resources/Storyboards/DetailViewPage.storyboard
  Hyangyu/Hyangyu/Sources/APIModels/CagetoryDisplayResponse.swift
  Hyangyu/Hyangyu/Sources/Extensions/UIImageView+Extension.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/DetailPageViewController.swift
Labels: bug, sorin

#41 [Feat] 내가 저장한 전시회 저장 및 취소 서버 연결하기 (#36)
  Hyangyu/Hyangyu/Resources/Storyboards/DetailViewPage.storyboard
  Hyangyu/Hyangyu/Sources/APIModels/MyPage.swift
  Hyangyu/Hyangyu/Sources/APIServices/SavedAPI/SavedAPI.swift
  Hyangyu/Hyangyu/Sources/APIServices/SavedAPI/SavedService.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/DetailPageViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/MyPage/MyExhibitionViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/MyPage/MyPageViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/MyPage/ProfileEditViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/MyPage/ProfileEditViewController.xib
Labels: sorin, feat, 서버연결

#46 [Feat] 전시회 리뷰 저장 서버 연결 (#42)
  Hyangyu/Hyangyu.xcodeproj/project.pbxproj
  Hyangyu/Hyangyu/Resources/Constants/URL.swift
  Hyangyu/Hyangyu/Resources/Storyboards/DetailViewPage.storyboard
  Hyangyu/Hyangyu/Sources/APIModels/Review.swift
  Hyangyu/Hyangyu/Sources/APIServices/ReviewAPI/ReviewAPI.swift
  Hyangyu/Hyangyu/Sources/APIServices/ReviewAPI/ReviewService.swift
  Hyangyu/Hyangyu/Sources/Extensions/UIViewController+Extensions.swift
  Hyangyu/Hyangyu/Sources/SceneDelegate.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/DetailPageViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/MyPage/ProfileEditViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/MyPage/SettingsViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/SignIn/SignInViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/SignUp/SignUpViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/WriteReviewViewController.swift
Labels: sorin, feat, 서버연결

#52 [feat] 리뷰 조회 구현중~
  Hyangyu/Hyangyu.xcodeproj/project.pbxproj
  Hyangyu/Hyangyu/Resources/Constants/URL.swift
  Hyangyu/Hyangyu/Resources/Storyboards/CategoryTab.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/DetailViewPage.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/MoreReviewPage.storyboard
  Hyangyu/Hyangyu/Sources/APIModels/ReviewDisplayResponse.swift
  Hyangyu/Hyangyu/Sources/APIServices/ReviewAPI/ShowReviewAPI.swift
  Hyangyu/Hyangyu/Sources/APIServices/ReviewAPI/ShowReviewService.swift
  Hyangyu/Hyangyu/Sources/Cells/ReviewCollectionViewCell.swift
  Hyangyu/Hyangyu/Sources/Cells/ReviewCollectionViewCell.xib
  Hyangyu/Hyangyu/Sources/ViewControllers/CategoryViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/DetailPageViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/MoreReviewViewController.swift
Labels: heesoo, feat

#54 [Feat] 스플래시 화면, 앱 아이콘, 로그인 화면 구현 (#43)
  Hyangyu/Hyangyu.xcodeproj/project.pbxproj
  Hyangyu/Hyangyu/Base.lproj/LaunchScreen.storyboard
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/loginBackground.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/loginBackground.imageset/loginBackground@1x.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/loginBackground.imageset/loginBackground@2x.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/loginBackground.imageset/loginBackground@3x.png
  Hyangyu/Hyangyu/Resources/Assets.xcassets/logo.imageset/Contents.json
  Hyangyu/Hyangyu/Resources/Assets.xcassets/logo.imageset/logo.png
  Hyangyu/Hyangyu/Resources/Storyboards/Login/Login.storyboard
  Hyangyu/Hyangyu/Sources/SceneDelegate.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/LoginViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/MyPage/SettingsViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/SignIn/SignInViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/SignUp/SignUpViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/TabBarViewController.swift
Labels: sorin, feat

#56 [Fix] 탭바 오류, 상세페이지 오류 해결
  Hyangyu/Hyangyu/Base.lproj/LaunchScreen.storyboard
  Hyangyu/Hyangyu/Resources/Storyboards/DetailViewPage.storyboard
  Hyangyu/Hyangyu/Sources/ViewControllers/DetailPageViewController.swift
  Hyangyu/Hyangyu/Sources/ViewControllers/TabBarViewController.swift
Labels: bug, sorin
